### ISSUE TITLE
Description of biobanks is not correct after applying filters

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-biobank-plots#16]
![screen shot 2018-05-17 at 08 51 57](https://user-images.githubusercontent.com/10075439/40160968-9b886a7e-59af-11e8-9137-3ddcbd63b00a.png)
![screen shot 2018-05-17 at 08 52 05](https://user-images.githubusercontent.com/10075439/40160976-9ec91a80-59af-11e8-9efa-10863608d1a5.png)

**Comment by ConnorStroomberg** [comment]
closed by https://github.com/molgenis/molgenis-app-biobank-plots/pull/17
